package org.houxg.pixiurss;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.houxg.pixiurss.Source;
import org.houxg.pixiurss.Article;

import org.houxg.pixiurss.SourceDao;
import org.houxg.pixiurss.ArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sourceDaoConfig;
    private final DaoConfig articleDaoConfig;

    private final SourceDao sourceDao;
    private final ArticleDao articleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sourceDaoConfig = daoConfigMap.get(SourceDao.class).clone();
        sourceDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        sourceDao = new SourceDao(sourceDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);

        registerDao(Source.class, sourceDao);
        registerDao(Article.class, articleDao);
    }
    
    public void clear() {
        sourceDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
    }

    public SourceDao getSourceDao() {
        return sourceDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

}
